In [1]:
!pip install gensim
import gensim
from gensim.models import Word2Vec, KeyedVectors

Collecting gensim
  Downloading gensim-4.4.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (8.4 kB)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.12/dist-packages (from gensim) (2.0.2)
Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from gensim) (1.16.3)
Requirement already satisfied: smart_open>=1.8.1 in /usr/local/lib/python3.12/dist-packages (from gensim) (7.5.1)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart_open>=1.8.1->gensim) (2.1.2)
Downloading gensim-4.4.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (27.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 18.5 MB/s eta 0:00:00
Installing collected packages: gensim
Successfully installed gensim-4.4.0

In [2]:
import gensim.downloader as api
wv = api.load('word2vec-google-news-300')
wv

[==================================================] 100.0% 1662.8/1662.8MB downloaded

In [3]:
import pandas as pd
message=pd.read_csv('/content/SMSSpamCollection',sep='\t',names=['label','message'])
message.head()

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [4]:
from nltk.stem.snowball import stopwords
# data cleaning and data processing
import re
import nltk
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [5]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [6]:
corpus=[]
for i in range(0,len(message)):
    review=re.sub('[^a-zA-Z]',' ',message['message'][i])
    review=review.lower()
    review=review.split()
    review=[ps.stem(word) for word in review ]
    review=' '.join(review)
    corpus.append(review)
    corpus

In [7]:
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [8]:
from gensim.utils import simple_preprocess
words=[]
for j in corpus:
  sent_tokenizer=nltk.sent_tokenize(j)
  for j in sent_tokenizer:
    words.append(simple_preprocess(j))

In [9]:
words

[['go',
  'until',
  'jurong',
  'point',
  'crazi',
  'avail',
  'onli',
  'in',
  'bugi',
  'great',
  'world',
  'la',
  'buffet',
  'cine',
  'there',
  'got',
  'amor',
  'wat'],
 ['ok', 'lar', 'joke', 'wif', 'oni'],
 ['free',
  'entri',
  'in',
  'wkli',
  'comp',
  'to',
  'win',
  'fa',
  'cup',
  'final',
  'tkt',
  'st',
  'may',
  'text',
  'fa',
  'to',
  'to',
  'receiv',
  'entri',
  'question',
  'std',
  'txt',
  'rate',
  'appli',
  'over'],
 ['dun', 'say', 'so', 'earli', 'hor', 'alreadi', 'then', 'say'],
 ['nah',
  'don',
  'think',
  'he',
  'goe',
  'to',
  'usf',
  'he',
  'live',
  'around',
  'here',
  'though'],
 ['freemsg',
  'hey',
  'there',
  'darl',
  'it',
  'been',
  'week',
  'now',
  'and',
  'no',
  'word',
  'back',
  'like',
  'some',
  'fun',
  'you',
  'up',
  'for',
  'it',
  'still',
  'tb',
  'ok',
  'xxx',
  'std',
  'chg',
  'to',
  'send',
  'to',
  'rcv'],
 ['even',
  'my',
  'brother',
  'is',
  'not',
  'like',
  'to',
  'speak',
  'with',
  'me',
  'they',
  'treat',
  'me',
  'like',
  'aid',
  'patent'],
 ['as',
  'per',
  'your',
  'request',
  'mell',
  'mell',
  'oru',
  'minnaminungint',
  'nurungu',
  'vettam',
  'ha',
  'been',
  'set',
  'as',
  'your',
  'callertun',
  'for',
  'all',
  'caller',
  'press',
  'to',
  'copi',
  'your',
  'friend',
  'callertun'],
 ['winner',
  'as',
  'valu',
  'network',
  'custom',
  'you',
  'have',
  'been',
  'select',
  'to',
  'receivea',
  'prize',
  'reward',
  'to',
  'claim',
  'call',
  'claim',
  'code',
  'kl',
  'valid',
  'hour',
  'onli'],
 ['had',
  'your',
  'mobil',
  'month',
  'or',
  'more',
  'entitl',
  'to',
  'updat',
  'to',
  'the',
  'latest',
  'colour',
  'mobil',
  'with',
  'camera',
  'for',
  'free',
  'call',
  'the',
  'mobil',
  'updat',
  'co',
  'free',
  'on'],
 ['gonna',
  'be',
  'home',
  'soon',
  'and',
  'don',
  'want',
  'to',
  'talk',
  'about',
  'thi',
  'stuff',
  'anymor',
  'tonight',
  've',
  'cri',
  'enough',
  'today'],
 ['six',
  'chanc',
  'to',
  'win',
  'cash',
  'from',
  'to',
  'pound',
  'txt',
  'csh',
  'and',
  'send',
  'to',
  'cost',
  'day',
  'day',
  'tsandc',
  'appli',
  'repli',
  'hl',
  'info'],
 ['urgent',
  'you',
  'have',
  'won',
  'week',
  'free',
  'membership',
  'in',
  'our',
  'prize',
  'jackpot',
  'txt',
  'the',
  'word',
  'claim',
  'to',
  'no',
  'www',
  'dbuk',
  'net',
  'lccltd',
  'pobox',
  'ldnw',
  'rw'],
 ['ve',
  'been',
  'search',
  'for',
  'the',
  'right',
  'word',
  'to',
  'thank',
  'you',
  'for',
  'thi',
  'breather',
  'promis',
  'wont',
  'take',
  'your',
  'help',
  'for',
  'grant',
  'and',
  'will',
  'fulfil',
  'my',
  'promis',
  'you',
  'have',
  'been',
  'wonder',
  'and',
  'bless',
  'at',
  'all',
  'time'],
 ['have', 'date', 'on', 'sunday', 'with', 'will'],
 ['to',
  'use',
  'your',
  'credit',
  'click',
  'the',
  'wap',
  'link',
  'in',
  'the',
  'next',
  'txt',
  'messag',
  'or',
  'click',
  'here',
  'http',
  'wap',
  'com',
  'qjkgighjjgcbl'],
 ['oh', 'watch', 'here'],
 ['eh',
  'rememb',
  'how',
  'spell',
  'hi',
  'name',
  'ye',
  'did',
  'he',
  'naughti',
  'make',
  'until',
  'wet'],
 ['fine',
  'if',
  'that',
  'the',
  'way',
  'feel',
  'that',
  'the',
  'way',
  'it',
  'gota'],
 ['england',
  'macedonia',
  'dont',
  'miss',
  'the',
  'goal',
  'team',
  'news',
  'txt',
  'ur',
  'nation',
  'team',
  'to',
  'eg',
  'england',
  'to',
  'tri',
  'wale',
  'scotland',
  'txt',
  'poboxox',
  'wq'],
 ['is', 'that', 'serious', 'how', 'you', 'spell', 'hi', 'name'],
 ['go', 'to', 'tri', 'for', 'month', 'ha', 'ha', 'onli', 'joke'],
 ['so', 'pay', 'first', 'lar', 'then', 'when', 'is', 'da', 'stock', 'comin'],
 ['aft',
  'finish',
  'my',
  'lunch',
  'then',
  'go',
  'str',
  'down',
  'lor',
  'ard',
  'smth',
  'lor',
  'finish',
  'ur',
  'lunch',
  'alreadi'],
 ['ffffffffff',
  'alright',
  'no',
  'way',
  'can',
  'meet',
  'up',
  'with',
  'you',
  'sooner'],
 ['just',
  'forc',
  'myself',
  'to',
  'eat',
  'slice',
  'realli',
  'not',
  'hungri',
  'tho',
  'thi',
  'suck',
  'mark',
  'is',
  'get',
  'worri',
  'he',
  'know',
  'sick',
  'when',
  'turn',
  'down',
  'pizza',
  'lol'],
 ['lol', 'your', 'alway', 'so', 'convinc'],
 ['did',
  'you',
  'catch',
  'the',
  'bu',
  'are',
  'you',
  'fri',
  'an',
  'egg',
  'did',
  'you',
  'make',
  'tea',
  'are',
  'you',
  'eat',
  'your',
  'mom',
  'left',
  'over',
  'dinner',
  'do',
  'you',
  'feel',
  'my',
  'love'],
 ['back',
  'amp',
  'we',
  're',
  'pack',
  'the',
  'car',
  'now',
  'll',
  'let',
  'you',
  'know',
  'if',
  'there',
  'room'],
 ['ahhh',
  'work',
  'vagu',
  'rememb',
  'that',
  'what',
  'doe',
  'it',
  'feel',
  'like',
  'lol'],
 ['wait',
  'that',
  'still',
  'not',
  'all',
  'that',
  'clear',
  'were',
  'you',
  'not',
  'sure',
  'about',
  'me',
  'be',
  'sarcast',
  'or',
  'that',
  'that',
  'whi',
  'doesn',
  'want',
  'to',
  'live',
  'with',
  'us'],
 ['yeah',
  'he',
  'got',
  'in',
  'at',
  'and',
  'wa',
  'apologet',
  'had',
  'fallen',
  'out',
  'and',
  'she',
  'wa',
  'actin',
  'like',
  'spoilt',
  'child',
  'and',
  'he',
  'got',
  'caught',
  'up',
  'in',
  'that',
  'till',
  'but',
  'we',
  'won',
  'go',
  'there',
  'not',
  'do',
  'too',
  'badli',
  'cheer',
  'you'],
 ['tell', 'me', 'anyth', 'about', 'you'],
 ['for',
  'fear',
  'of',
  'faint',
  'with',
  'the',
  'of',
  'all',
  'that',
  'housework',
  'you',
  'just',
  'did',
  'quick',
  'have',
  'cuppa'],
 ['thank',
  'for',
  'your',
  'subscript',
  'to',
  'rington',
  'uk',
  'your',
  'mobil',
  'will',
  'be',
  'charg',
  'month',
  'pleas',
  'confirm',
  'by',
  'repli',
  'ye',
  'or',
  'no',
  'if',
  'you',
  'repli',
  'no',
  'you',
  'will',
  'not',
  'be',
  'charg'],
 ['yup',
  'ok',
  'go',
  'home',
  'look',
  'at',
  'the',
  'time',
  'then',
  'msg',
  'again',
  'xuhui',
  'go',
  'to',
  'learn',
  'on',
  'nd',
  'may',
  'too',
  'but',
  'her',
  'lesson',
  'is',
  'at',
  'am'],
 ['oop', 'll', 'let', 'you', 'know', 'when', 'my', 'roommat', 'done'],
 ['see', 'the', 'letter', 'on', 'my', 'car'],
 ['anyth', 'lor', 'decid'],
 ['hello',
  'how',
  'you',
  'and',
  'how',
  'did',
  'saturday',
  'go',
  'wa',
  'just',
  'text',
  'to',
  'see',
  'if',
  'you',
  'decid',
  'to',
  'do',
  'anyth',
  'tomo',
  'not',
  'that',
  'tri',
  'to',
  'invit',
  'myself',
  'or',
  'anyth'],
 ['pl',
  'go',
  'ahead',
  'with',
  'watt',
  'just',
  'want',
  'to',
  'be',
  'sure',
  'do',
  'have',
  'great',
  'weekend',
  'abiola'],
 ['did',
  'forget',
  'to',
  'tell',
  'you',
  'want',
  'you',
  'need',
  'you',
  'crave',
  'you',
  'but',
  'most',
  'of',
  'all',
  'love',
  'you',
  'my',
  'sweet',
  'arabian',
  'steed',
  'mmmmmm',
  'yummi'],
 ['rodger',
  'burn',
  'msg',
  'we',
  'tri',
  'to',
  'call',
  'you',
  're',
  'your',
  'repli',
  'to',
  'our',
  'sm',
  'for',
  'free',
  'nokia',
  'mobil',
  'free',
  'camcord',
  'pleas',
  'call',
  'now',
  'for',
  'deliveri',
  'tomorrow'],
 ['who', 'are', 'you', 'see'],
 ['great',
  'hope',
  'you',
  'like',
  'your',
  'man',
  'well',
  'endow',
  'am',
  'lt',
  'gt',
  'inch'],
 ['no', 'call', 'messag', 'miss', 'call'],
 ['didn', 'you', 'get', 'hep', 'immunis', 'in', 'nigeria'],
 ['fair', 'enough', 'anyth', 'go', 'on'],
 ['yeah',
  'hope',
  'if',
  'tyler',
  'can',
  'do',
  'it',
  'could',
  'mayb',
  'ask',
  'around',
  'bit'],
 ['don',
  'know',
  'how',
  'stubborn',
  'am',
  'didn',
  'even',
  'want',
  'to',
  'go',
  'to',
  'the',
  'hospit',
  'kept',
  'tell',
  'mark',
  'not',
  'weak',
  'sucker',
  'hospit',
  'are',
  'for',
  'weak',
  'sucker'],
 ['what',
  'you',
  'think',
  'about',
  'me',
  'first',
  'time',
  'you',
  'saw',
  'me',
  'in',
  'class'],
 ['gram',
  'usual',
  'run',
  'like',
  'lt',
  'gt',
  'half',
  'eighth',
  'is',
  'smarter',
  'though',
  'and',
  'get',
  'you',
  'almost',
  'whole',
  'second',
  'gram',
  'for',
  'lt',
  'gt'],
 ['fyi',
  'ha',
  'ride',
  'earli',
  'tomorrow',
  'morn',
  'but',
  'he',
  'crash',
  'at',
  'our',
  'place',
  'tonight'],
 ['wow',
  'never',
  'realiz',
  'that',
  'you',
  'were',
  'so',
  'embarass',
  'by',
  'your',
  'accomod',
  'thought',
  'you',
  'like',
  'it',
  'sinc',
  'wa',
  'do',
  'the',
  'best',
  'could',
  'and',
  'you',
  'alway',
  'seem',
  'so',
  'happi',
  'about',
  'the',
  'cave',
  'sorri',
  'didn',
  'and',
  'don',
  'have',
  'more',
  'to',
  'give',
  'sorri',
  'offer',
  'sorri',
  'your',
  'room',
  'wa',
  'so',
  'embarass'],
 ['sm',
  'ac',
  'sptv',
  'the',
  'new',
  'jersey',
  'devil',
  'and',
  'the',
  'detroit',
  'red',
  'wing',
  'play',
  'ice',
  'hockey',
  'correct',
  'or',
  'incorrect',
  'end',
  'repli',
  'end',
  'sptv'],
 ['do',
  'you',
  'know',
  'what',
  'mallika',
  'sherawat',
  'did',
  'yesterday',
  'find',
  'out',
  'now',
  'lt',
  'url',
  'gt'],
 ['congrat',
  'year',
  'special',
  'cinema',
  'pass',
  'for',
  'is',
  'your',
  'call',
  'now',
  'suprman',
  'matrix',
  'starwar',
  'etc',
  'all',
  'free',
  'bx',
  'ip',
  'we',
  'pm',
  'dont',
  'miss',
  'out'],
 ['sorri', 'll', 'call', 'later', 'in', 'meet'],
 ['tell', 'where', 'you', 'reach'],
 ['ye', 'gauti', 'and', 'sehwag', 'out', 'of', 'odi', 'seri'],
 ['your',
  'gonna',
  'have',
  'to',
  'pick',
  'up',
  'burger',
  'for',
  'yourself',
  'on',
  'your',
  'way',
  'home',
  'can',
  'even',
  'move',
  'pain',
  'is',
  'kill',
  'me'],
 ['ha', 'ha', 'ha', 'good', 'joke', 'girl', 'are', 'situat', 'seeker'],
 ['it', 'part', 'of', 'check', 'iq'],
 ['sorri',
  'my',
  'roommat',
  'took',
  'forev',
  'it',
  'ok',
  'if',
  'come',
  'by',
  'now'],
 ['ok',
  'lar',
  'doubl',
  'check',
  'wif',
  'da',
  'hair',
  'dresser',
  'alreadi',
  'he',
  'said',
  'wun',
  'cut',
  'short',
  'he',
  'said',
  'will',
  'cut',
  'until',
  'look',
  'nice'],
 ['as',
  'valu',
  'custom',
  'am',
  'pleas',
  'to',
  'advis',
  'you',
  'that',
  'follow',
  'recent',
  'review',
  'of',
  'your',
  'mob',
  'no',
  'you',
  'are',
  'award',
  'with',
  'bonu',
  'prize',
  'call'],
 ['today',
  'is',
  'song',
  'dedic',
  'day',
  'which',
  'song',
  'will',
  'dedic',
  'for',
  'me',
  'send',
  'thi',
  'to',
  'all',
  'ur',
  'valuabl',
  'frnd',
  'but',
  'first',
  'rpli',
  'me'],
 ['urgent',
  'ur',
  'award',
  'complimentari',
  'trip',
  'to',
  'eurodisinc',
  'trav',
  'aco',
  'entri',
  'or',
  'to',
  'claim',
  'txt',
  'di',
  'to',
  'morefrmmob',
  'ls',
  'aj'],
 ['did',
  'you',
  'hear',
  'about',
  'the',
  'new',
  'divorc',
  'barbi',
  'it',
  'come',
  'with',
  'all',
  'of',
  'ken',
  'stuff'],
 ['plane', 'to', 'give', 'on', 'thi', 'month', 'end'],
 ['wah', 'lucki', 'man', 'then', 'can', 'save', 'money', 'hee'],
 ['finish', 'class', 'where', 'are', 'you'],
 ['hi', 'babe', 'im', 'at', 'home', 'now', 'wanna', 'do', 'someth', 'xx'],
 ['where', 'are', 'you', 'how', 'did', 'you', 'perform'],
 ['can', 'call', 'me', 'now'],
 ['am', 'wait', 'machan', 'call', 'me', 'onc', 'you', 'free'],
 ['that',
  'cool',
  'am',
  'gentleman',
  'and',
  'will',
  'treat',
  'you',
  'with',
  'digniti',
  'and',
  'respect'],
 ['like', 'you', 'peopl', 'veri', 'much', 'but', 'am', 'veri', 'shi', 'pa'],
 ['doe', 'not', 'oper', 'after', 'lt', 'gt', 'or', 'what'],
 ['it',
  'not',
  'the',
  'same',
  'here',
  'still',
  'look',
  'for',
  'job',
  'how',
  'much',
  'do',
  'ta',
  'earn',
  'there'],
 ['sorri', 'll', 'call', 'later'],
 ['did', 'you', 'call', 'me', 'just', 'now', 'ah'],
 ['ok', 'am', 'on', 'the', 'way', 'to', 'home', 'hi', 'hi'],
 ['you', 'will', 'be', 'in', 'the', 'place', 'of', 'that', 'man'],
 ['yup', 'next', 'stop'],
 ['call', 'you', 'later', 'don', 'have', 'network', 'if', 'urgnt', 'sm', 'me'],
 ['for',
  'real',
  'when',
  'get',
  'on',
  'yo',
  'onli',
  'need',
  'more',
  'ticket',
  'and',
  'one',
  'more',
  'jacket',
  'and',
  'done',
  'alreadi',
  'use',
  'all',
  'my',
  'multi'],
 ['ye',
  'start',
  'to',
  'send',
  'request',
  'to',
  'make',
  'it',
  'but',
  'pain',
  'came',
  'back',
  'so',
  'back',
  'in',
  'bed',
  'doubl',
  'coin',
  'at',
  'the',
  'factori',
  'too',
  'gotta',
  'cash',
  'in',
  'all',
  'my',
  'nitro'],
 ['realli', 'not', 'up', 'to', 'it', 'still', 'tonight', 'babe'],
 ['ela', 'kano', 'il', 'download', 'come', 'wen', 'ur', 'free'],
 ['yeah',
  'do',
  'don',
  'stand',
  'to',
  'close',
  'tho',
  'you',
  'll',
  'catch',
  'someth'],
 ['sorri',
  'to',
  'be',
  'pain',
  'is',
  'it',
  'ok',
  'if',
  'we',
  'meet',
  'anoth',
  'night',
  'spent',
  'late',
  'afternoon',
  'in',
  'casualti',
  'and',
  'that',
  'mean',
  'haven',
  'done',
  'ani',
  'of',
  'stuff',
  'moro',
  'and',
  'that',
  'includ',
  'all',
  'my',
  'time',
  'sheet',
  'and',
  'that',
  'sorri'],
 ['smile',
  'in',
  'pleasur',
  'smile',
  'in',
  'pain',
  'smile',
  'when',
  'troubl',
  'pour',
  'like',
  'rain',
  'smile',
  'when',
  'sum',
  'hurt',
  'smile',
  'becoz',
  'someon',
  'still',
  'love',
  'to',
  'see',
  'smile'],
 ['pleas',
  'call',
  'our',
  'custom',
  'servic',
  'repres',
  'on',
  'between',
  'am',
  'pm',
  'as',
  'you',
  'have',
  'won',
  'guarante',
  'cash',
  'or',
  'prize'],
 ['havent',
  'plan',
  'to',
  'buy',
  'later',
  'check',
  'alreadi',
  'lido',
  'onli',
  'got',
  'show',
  'in',
  'afternoon',
  'finish',
  'work',
  'alreadi'],
 ['your',
  'free',
  'rington',
  'is',
  'wait',
  'to',
  'be',
  'collect',
  'simpli',
  'text',
  'the',
  'password',
  'mix',
  'to',
  'to',
  'verifi',
  'get',
  'usher',
  'and',
  'britney',
  'fml',
  'po',
  'box',
  'mk',
  'ppw'],
 ['watch', 'telugu', 'movi', 'wat', 'abt'],
 ['see',
  'when',
  'we',
  'finish',
  'we',
  'have',
  'load',
  'of',
  'loan',
  'to',
  'pay'],
 ['hi',
  'wk',
  'been',
  'ok',
  'on',
  'hol',
  'now',
  'ye',
  'on',
  'for',
  'bit',
  'of',
  'run',
  'forgot',
  'that',
  'have',
  'hairdress',
  'appoint',
  'at',
  'four',
  'so',
  'need',
  'to',
  'get',
  'home',
  'shower',
  'beforehand',
  'doe',
  'that',
  'caus',
  'prob',
  'for'],
 ['see', 'cup', 'of', 'coffe', 'anim'],
 ['pleas', 'don', 'text', 'me', 'anymor', 'have', 'noth', 'els', 'to', 'say'],
 ['okay',
  'name',
  'ur',
  'price',
  'as',
  'long',
  'as',
  'it',
  'legal',
  'wen',
  'can',
  'pick',
  'them',
  'up',
  'ave',
  'am',
  'xx'],
 ['still',
  'look',
  'for',
  'car',
  'to',
  'buy',
  'and',
  'have',
  'not',
  'gone',
  'the',
  'drive',
  'test',
  'yet'],
 ['as',
  'per',
  'your',
  'request',
  'mell',
  'mell',
  'oru',
  'minnaminungint',
  'nurungu',
  'vettam',
  'ha',
  'been',
  'set',
  'as',
  'your',
  'callertun',
  'for',
  'all',
  'caller',
  'press',
  'to',
  'copi',
  'your',
  'friend',
  'callertun'],
 ['wow',
  'you',
  're',
  'right',
  'didn',
  'mean',
  'to',
  'do',
  'that',
  'guess',
  'onc',
  'gave',
  'up',
  'on',
  'boston',
  'men',
  'and',
  'chang',
  'my',
  'search',
  'locat',
  'to',
  'nyc',
  'someth',
  'chang',
  'cuz',
  'on',
  'my',
  'signin',
  'page',
  'it',
  'still',
  'say',
  'boston'],
 ['umma', 'my', 'life', 'and', 'vava', 'umma', 'love', 'you', 'lot', 'dear'],
 ['thank',
  'lot',
  'for',
  'your',
  'wish',
  'on',
  'my',
  'birthday',
  'thank',
  'you',
  'for',
  'make',
  'my',
  'birthday',
  'truli',
  'memor'],
 ['aight', 'll', 'hit', 'you', 'up', 'when', 'get', 'some', 'cash'],
 ['how',
  'would',
  'my',
  'ip',
  'address',
  'test',
  'that',
  'consid',
  'my',
  'comput',
  'isn',
  'minecraft',
  'server'],
 ['know',
  'grumpi',
  'old',
  'peopl',
  'my',
  'mom',
  'wa',
  'like',
  'you',
  'better',
  'not',
  'be',
  'lie',
  'then',
  'again',
  'am',
  'alway',
  'the',
  'one',
  'to',
  'play',
  'joke'],
 ['dont', 'worri', 'guess', 'he', 'busi'],
 ['what', 'is', 'the', 'plural', 'of', 'the', 'noun', 'research'],
 ['go', 'for', 'dinner', 'msg', 'you', 'after'],
 ['ok',
  'wif',
  'it',
  'co',
  'like',
  'tri',
  'new',
  'thing',
  'but',
  'scare',
  'dun',
  'like',
  'mah',
  'co',
  'said',
  'not',
  'too',
  'loud'],
 ['gent',
  'we',
  'are',
  'tri',
  'to',
  'contact',
  'you',
  'last',
  'weekend',
  'draw',
  'show',
  'that',
  'you',
  'won',
  'prize',
  'guarante',
  'call',
  'claim',
  'code',
  'valid',
  'hr',
  'onli',
  'ppm'],
 ['wa',
  'ur',
  'openin',
  'sentenc',
  'veri',
  'formal',
  'anyway',
  'fine',
  'too',
  'juz',
  'tt',
  'eatin',
  'too',
  'much',
  'puttin',
  'on',
  'weight',
  'haha',
  'so',
  'anythin',
  'special',
  'happen'],
 ['as',
  'enter',
  'my',
  'cabin',
  'my',
  'pa',
  'said',
  'happi',
  'day',
  'boss',
  'felt',
  'special',
  'she',
  'askd',
  'me',
  'lunch',
  'after',
  'lunch',
  'she',
  'invit',
  'me',
  'to',
  'her',
  'apart',
  'we',
  'went',
  'there'],
 ['you',
  'are',
  'winner',
  'have',
  'been',
  'special',
  'select',
  'receiv',
  'or',
  'holiday',
  'flight',
  'inc',
  'speak',
  'to',
  'live',
  'oper',
  'claim',
  'min'],
 ['goodo',
  'ye',
  'we',
  'must',
  'speak',
  'friday',
  'egg',
  'potato',
  'ratio',
  'for',
  'tortilla',
  'need'],
 ['hmm',
  'my',
  'uncl',
  'just',
  'inform',
  'me',
  'that',
  'he',
  'pay',
  'the',
  'school',
  'directli',
  'so',
  'pl',
  'buy',
  'food'],
 ['privat',
  'your',
  'account',
  'statement',
  'for',
  'show',
  'unredeem',
  'bonu',
  'point',
  'to',
  'claim',
  'call',
  'identifi',
  'code',
  'expir'],
 ['urgent',
  'your',
  'mobil',
  'no',
  'wa',
  'award',
  'bonu',
  'caller',
  'prize',
  'on',
  'thi',
  'is',
  'our',
  'final',
  'tri',
  'to',
  'contact',
  'call',
  'from',
  'landlin',
  'box',
  'wr',
  'ppm'],
 ['here',
  'is',
  'my',
  'new',
  'address',
  'appl',
  'pair',
  'all',
  'that',
  'malarki'],
 ['today',
  'voda',
  'number',
  'end',
  'are',
  'select',
  'to',
  'receiv',
  'award',
  'if',
  'you',
  'have',
  'match',
  'pleas',
  'call',
  'quot',
  'claim',
  'code',
  'standard',
  'rate',
  'app'],
 ['am', 'go', 'to', 'sao', 'mu', 'today', 'will', 'be', 'done', 'onli', 'at'],
 ['predict', 'wat', 'time', 'll', 'finish', 'buy'],
 ['good', 'stuff', 'will', 'do'],
 ['just',
  'so',
  'that',
  'you',
  'know',
  'yetund',
  'hasn',
  'sent',
  'money',
  'yet',
  'just',
  'sent',
  'her',
  'text',
  'not',
  'to',
  'bother',
  'send',
  'so',
  'it',
  'over',
  'you',
  'dont',
  'have',
  'to',
  'involv',
  'yourself',
  'in',
  'anyth',
  'shouldn',
  'have',
  'impos',
  'anyth',
  'on',
  'you',
  'in',
  'the',
  'first',
  'place',
  'so',
  'for',
  'that',
  'apologis'],
 ['are', 'you', 'there', 'in', 'room'],
 ['hey',
  'girl',
  'how',
  'hope',
  'well',
  'me',
  'an',
  'del',
  'bak',
  'again',
  'long',
  'time',
  'no',
  'give',
  'me',
  'call',
  'sum',
  'time',
  'from',
  'lucyxx'],
 ['how', 'much', 'doe', 'it', 'cost'],
 ['home'],
 ['dear', 'will', 'call', 'tmorrow', 'pl', 'accomod'],
 ['first', 'answer', 'my', 'question'],
 ['sunshin',
  'quiz',
  'wkli',
  'win',
  'top',
  'soni',
  'dvd',
  'player',
  'if',
  'know',
  'which',
  'countri',
  'the',
  'algarv',
  'is',
  'in',
  'txt',
  'ansr',
  'to',
  'sp',
  'tyron'],
 ['want',
  'get',
  'laid',
  'tonight',
  'want',
  'real',
  'dog',
  'locat',
  'sent',
  'direct',
  'ur',
  'mob',
  'join',
  'the',
  'uk',
  'largest',
  'dog',
  'network',
  'bt',
  'txting',
  'gravel',
  'to',
  'nt',
  'ec',
  'msg'],
 ['onli', 'haf', 'msn', 'it', 'yiju', 'hotmail', 'com'],
 ['he', 'is', 'there', 'you', 'call', 'and', 'meet', 'him'],
 ['no', 'no', 'will', 'check', 'all', 'room', 'befor', 'activ'],
 ['you',
  'll',
  'not',
  'rcv',
  'ani',
  'more',
  'msg',
  'from',
  'the',
  'chat',
  'svc',
  'for',
  'free',
  'hardcor',

In [10]:
#model training
model=Word2Vec(words)
#t get the all the vocabulary
model.wv.index_to_key

['to',
 'you',
 'the',
 'and',
 'it',
 'in',
 'is',
 'me',
 'my',
 'for',
 'your',
 'call',
 'that',
 'of',
 'have',
 'on',
 'now',
 'do',
 'are',
 'can',
 'so',
 'go',
 'get',
 'but',
 'not',
 'be',
 'or',
 'we',
 'at',
 'will',
 'ur',
 'if',
 'with',
 'no',
 'just',
 'thi',
 'how',
 'gt',
 'lt',
 'up',
 'what',
 'come',
 'when',
 'day',
 'ok',
 'free',
 'from',
 'all',
 'out',
 'know',
 'll',
 'love',
 'like',
 'time',
 'good',
 'want',
 'am',
 'then',
 'got',
 'wa',
 'there',
 'he',
 'text',
 'onli',
 'send',
 'hi',
 'txt',
 'need',
 'one',
 'as',
 'today',
 'by',
 'take',
 'stop',
 'see',
 'don',
 'she',
 'home',
 'about',
 'think',
 'repli',
 'lor',
 'sorri',
 'tell',
 'still',
 'mobil',
 'back',
 'da',
 'our',
 'dont',
 'make',
 'phone',
 'pleas',
 'week',
 'say',
 'new',
 'work',
 'they',
 'later',
 'pl',
 'ani',
 'hope',
 'her',
 'miss',
 'ha',
 'ask',
 'did',
 'co',
 'msg',
 'been',
 'min',
 'meet',
 'an',
 'some',
 'dear',
 'night',
 'messag',
 'who',
 'here',
 'happi',
 'wait',
 'well',
 'where',
 'give',
 're',
 'thing',
 'tri',
 'much',
 'great',
 'oh',
 'claim',
 'wat',
 'hey',
 'him',
 'number',
 'more',
 'too',
 'thank',
 'friend',
 'had',
 'way',
 'ye',
 'www',
 've',
 'should',
 'let',
 'prize',
 'feel',
 'won',
 'right',
 'even',
 'tomorrow',
 'win',
 'pick',
 'alreadi',
 'tone',
 'after',
 'care',
 'said',
 'cash',
 'im',
 'amp',
 'leav',
 'yeah',
 'realli',
 'babe',
 'find',
 'whi',
 'life',
 'them',
 'morn',
 'veri',
 'sleep',
 'last',
 'keep',
 'servic',
 'year',
 'uk',
 'nokia',
 'sure',
 'would',
 'buy',
 'anyth',
 'com',
 'use',
 'contact',
 'start',
 'also',
 'lol',
 'everi',
 'wish',
 'urgent',
 'look',
 'smile',
 'befor',
 'sent',
 'end',
 'over',
 'show',
 'someth',
 'watch',
 'award',
 'gud',
 'again',
 'us',
 'finish',
 'cant',
 'place',
 'box',
 'first',
 'help',
 'other',
 'person',
 'guy',
 'someon',
 'special',
 'chat',
 'went',
 'nice',
 'were',
 'next',
 'tonight',
 'custom',
 'off',
 'late',
 'which',
 'talk',
 'soon',
 'word',
 'around',
 'collect',
 'money',
 'could',
 'mani',
 'name',
 'per',
 'ya',
 'plan',
 'sm',
 'alway',
 'gonna',
 'wan',
 'down',
 'live',
 'minut',
 'lot',
 'check',
 'shop',
 'pm',
 'dun',
 'st',
 'told',
 'mean',
 'hello',
 'heart',
 'girl',
 'fine',
 'month',
 'hour',
 'may',
 'haha',
 'guarante',
 'peopl',
 'reach',
 'best',
 'th',
 'thk',
 'happen',
 'yet',
 'same',
 'offer',
 'done',
 'god',
 'ppm',
 'thought',
 'play',
 'didn',
 'cost',
 'fuck',
 'line',
 'holiday',
 'class',
 'stuff',
 'bit',
 'man',
 'car',
 'lunch',
 'receiv',
 'enjoy',
 'few',
 'ill',
 'hous',
 'draw',
 'wk',
 'job',
 'never',
 'mayb',
 'eat',
 'problem',
 'cs',
 'worri',
 'mind',
 'readi',
 'account',
 'hr',
 'better',
 'cool',
 'yup',
 'dat',
 'guess',
 'drive',
 'long',
 'rington',
 'pay',
 'date',
 'pobox',
 'rate',
 'quit',
 'game',
 'boy',
 'weekend',
 'chanc',
 'luv',
 'real',
 'half',
 'wonder',
 'latest',
 'world',
 'bring',
 'book',
 'than',
 'becaus',
 'sir',
 'bt',
 'po',
 'yo',
 'room',
 'pic',
 'voucher',
 'noth',
 'wanna',
 'sweet',
 'camera',
 'lar',
 'shit',
 'big',
 'liao',
 'join',
 'anoth',
 'charg',
 'question',
 'put',
 'kiss',
 'into',
 'stay',
 'age',
 'landlin',
 'birthday',
 'ah',
 'dinner',
 'select',
 'xxx',
 'land',
 'ever',
 'might',
 'video',
 'ju',
 'rememb',
 'network',
 'speak',
 'actual',
 'anyway',
 'hear',
 'wont',
 'appli',
 'probabl',
 'orang',
 'two',
 'babi',
 'thanx',
 'tv',
 'dream',
 'aight',
 'chang',
 'hurt',
 'bed',
 'pa',
 'onc',
 'di',
 'run',
 'nd',
 'fun',
 'earli',
 'final',
 'point',
 'princess',
 'bad',
 'den',
 'offic',
 'sat',
 'shall',
 'nite',
 'answer',
 'forgot',
 'part',
 'doe',
 'left',
 'dunno',
 'made',
 'gift',
 'wake',
 'walk',
 'easi',
 'between',
 'pain',
 'code',
 'dad',
 'wife',
 'true',
 'didnt',
 'everyth',
 'face',
 'sound',
 'leh',
 'littl',
 'mail',
 'xx',
 'frnd',
 'bu',
 'mate',
 'town',
 'bore',
 'detail',
 'those',
 'yr',
 'school',
 'movi',
 'afternoon',
 'pound',
 'enough',
 'await',
 'while',
 'poli',
 'post',
 'read',
 'lose',
 'tmr',
 'without',
 'most',
 'entri',
 'import',
 'hav',
 'xma',
 'sexi',
 'must',
 'test',
 'price',
 'okay',
 'came',
 'sinc',
 'decid',
 'credit',
 'updat',
 'valid',
 'though',
 'wif',
 'until',
 'drink',
 'wot',
 'abl',
 'smoke',
 'til',
 'abt',
 'close',
 'mob',
 'lesson',
 'colour',
 'set',
 'goe',
 'plu',
 'away',
 'de',
 'plz',
 'music',
 'decim',
 'bath',
 'order',
 'enter',
 'juz',
 'haven',
 'wen',
 'drop',
 'attempt',
 'beauti',
 'dude',
 'weekli',
 'hand',
 'top',
 'busi',
 'els',
 'havent',
 'hair',
 'doubl',
 'yesterday',
 'saw',
 'till',
 'alright',
 'lei',
 'goin',
 'onlin',
 'these',
 'friendship',
 'optout',
 'head',
 'oso',
 'id',
 'coz',
 'haf',
 'food',
 'trip',
 'invit',
 'net',
 'famili',
 'sch',
 'listen',
 'either',
 'club',
 'hot',
 'ring',
 'hold',
 'gr',
 'open',
 'player',
 'inform',
 'address',
 'yourself',
 'deliveri',
 'ard',
 'nation',
 'search',
 'sad',
 'togeth',
 'sae',
 'tot',
 'suit',
 'mth',
 'full',
 'wid',
 'both',
 'stori',
 'touch',
 'si',
 'believ',
 'complet',
 'nt',
 'caus',
 'bonu',
 'second',
 'mom',
 'http',
 'brother',
 'murder',
 'email',
 'train',
 'mum',
 'eve',
 'huh',
 'reason',
 'chikku',
 'row',
 'oki',
 'die',
 'noe',
 'studi',
 'content',
 'match',
 'old',
 'forget',
 'info',
 'anyon',
 'rite',
 'pub',
 'simpl',
 'unsubscrib',
 'park',
 'wil',
 'break',
 'awesom',
 'parent',
 'everyon',
 'dog',
 'expir',
 'privat',
 'took',
 'congrat',
 'tomo',
 'doesn',
 'fri',
 'aft',
 'news',
 'hl',
 'treat',
 'auction',
 'sell',
 'laugh',
 'neva',
 'mine',
 'opt',
 'gd',
 'current',
 'valentin',
 'sister',
 'card',
 'sort',
 'choos',
 'angri',
 'reveal',
 'compani',
 'tc',
 'fanci',
 'statement',
 'prob',
 'download',
 'move',
 'tho',
 'valu',
 'caller',
 'avail',
 'alon',
 'understand',
 'gal',
 'knw',
 'sun',
 'whatev',
 'visit',
 'forward',
 'colleg',
 'found',
 'worth',
 'carlo',
 'bank',
 'each',
 'type',
 'ticket',
 'lucki',
 'pass',
 'seem',
 'joke',
 'surpris',
 'parti',
 'sit',
 'fast',
 'sub',
 'outsid',
 'nyt',
 'kind',
 'welcom',
 'bout',
 'mobileupd',
 'return',
 'fone',
 'far',
 'anytim',
 'congratul',
 'secret',
 'gbp',
 'exam',
 'bill',
 'ga',
 'rs',
 'boytoy',
 'log',
 'hard',
 'ltd',
 'ni',
 'identifi',
 'uncl',
 'friday',
 'hit',
 'gone',
 'oper',
 'save',
 'song',
 'usual',
 'saturday',
 'smth',
 'winner',
 'tht',
 'chennai',
 'least',
 'wrong',
 'drug',
 'clean',
 'sea',
 'pretti',
 'nope',
 'term',
 'cum',
 'remov',
 'differ',
 'ad',
 'project',
 'interest',
 'light',
 'tel',
 'case',
 'oredi',
 'goodmorn',
 'darlin',
 'mrng',
 'wit',
 'their',
 'quiz',
 'mu',
 'rain',
 'follow',
 'cut',
 'camcord',
 'confirm',
 'crazi',
 'wasn',
 'support',
 'earlier',
 'snow',
 'kid',
 'savamob',
 'frm',
 'scream',
 'suppos',
 'ten',
 'rock',
 'jay',
 'blue',
 'own',
 'unlimit',
 'cd',
 'fix',
 'fr',
 'meant',
 'cours',
 'spend',
 'tire',
 'hmm',
 'isn',
 'comput',
 'correct',
 'whole',
 'hungri',
 'wq',
 'sunday',
 'freemsg',
 'wkli',
 'father',
 'fren',
 'john',
 'luck',
 'film',
 'na',
 'gn',
 'knew',
 'store',
 'eye',
 'sex',
 'paper',
 'area',
 'yar',
 'marri',
 'redeem',
 'un',
 'within',
 'fight',
 'sk',
 'india',
 'ass',
 'coupl',
 'motorola',
 'moment',
 'ago',
 'figur',
 'christma',
 'lost',
 'normal',
 'bslvyl',
 'stupid',
 'singl',
 'dnt',
 'side',
 'march',
 'balanc',
 'mr',
 'hmmm',
 'joy',
 'wine',
 'pray',
 'activ',
 'felt',
 'mah',
 'shower',
 'load',
 'hee',
 'etc',
 'almost',
 'catch',
 'turn',
 'eh',
 'promis',
 'reward',
 'press',
 'difficult',
 'grin',
 'fill',
 'heard',
 'photo',
 'extra',
 'ugh',
 'xy',
 'darren',
 'gym',
 'remind',
 'through',
 'max',
 'ladi',
 'ipod',
 'rent',
 'doin',
 'rental',
 'slow',
 'seen',
 'met',
 'ish',
 'via',
 'ge',
 'swing',
 'disturb',
 'laptop',
 'teach',
 'bcoz',
 'semest',
 'connect',
 'deal',
 'safe',
 'sometim',
 'direct',
 'askd',
 'stand',
 'gotta',
 'complimentari',
 'red',
 'ac',
 'wow',
 'hospit',
 'crave',
 'cheer',
 'comp',
 'polic',
 'slowli',
 'fact',
 'fantasi',
 'nobodi',
 'cancel',
 'convey',
 'truth',
 'asap',
 'whenev',
 'fall',
 'possibl',
 'subscrib',
 'idea',
 'ts',
 'noon',
 'door',
 'warm',
 'blood',
 'member',
 'silent',
 'monday',
 'ldn',
 'yep',
 'share',
 'discount',
 'hg',
 'ex',
 'weed',
 'small',
 'pete',
 'rest',
 'somebodi',
 'hmv',
 'wana',
 'lover',
 'expect',
 'road',
 'regist',
 'kate',
 'orchard',
 'muz',
 'lovabl',
 'txting',
 'page',
 'loan',
 'includ',
 'rpli',
 'abiola',
 'comin',
 'eg',
 'link',
 'wap',
 'copi',
 'request',
 'usf',
 'std',
 'empti',
 'med',
 'cook',
 'excus',
 'hw',
 'cover',
 'write',
 'bb',
 'energi',
 'doctor',
 'digit',
 'regard',
 'rd',
 'sale',
 'cr',
 'ntt',
 'otherwis',
 'poor',
 'wed',
 'gettin',
 'bag',
 'getz',
 'summer',
 'glad',
 'fantast',
 'gap',
 'king',
 'ho',
 'indian',
 'em',
 'cheap',
 'across',
 'children',
 'less',
 'opinion',
 'near',
 'water',
 'style',
 'wc',
 'voic',
 'mm',
 'mistak',
 'woke',
 'rakhesh',
 'custcar',
 'access',
 'immedi',
 'record',
 'merri',
 'somewher',
 'tonit',
 'deep',
 'admir',
 'kick',
 'street',
 'sign',
 'trust',
 'wast',
 'soni',
 'del',
 'quot',
 'apart',
 'men',
 'gave',
 'repres',
 'il',
 'recent',
 'short',
 'forev',
 'situat',
 'oop',
 'sick',
 'myself',
 'england',
 'bless',
 'callertun',
 'nah',
 'cup',
 'la',
 'tear',
 'sofa',
 'colleagu',
 'flag',
 'thinkin',
 'list',
 'excel',
 'arriv',
 'natur',
 'total',
 ...]

In [11]:
model.corpus_count

5569

In [12]:
model.epochs

5

In [13]:
model.wv.similar_by_word('good')

[('whi', 0.9983308911323547),
 ('hope', 0.9983052015304565),
 ('my', 0.9982569813728333),
 ('and', 0.9982355237007141),
 ('about', 0.9982162714004517),
 ('day', 0.9982114434242249),
 ('thing', 0.998206377029419),
 ('but', 0.9981836676597595),
 ('well', 0.9981175065040588),
 ('feel', 0.9981151223182678)]

In [14]:
model.wv['good'].shape,words[0]

((100,),
 ['go',
  'until',
  'jurong',
  'point',
  'crazi',
  'avail',
  'onli',
  'in',
  'bugi',
  'great',
  'world',
  'la',
  'buffet',
  'cine',
  'there',
  'got',
  'amor',
  'wat'])

In [15]:
def avg_word2vec(doc):
    # remove out-of-vocabulary words
    # sent = [word for word in doc if word in model.wv.index_to_key]
    # print(sent)

    return np.mean(
        [model.wv[word] for word in doc if word in model.wv.index_to_key]
        or [np.zeros(len(model.wv.index_to_key))],
        axis=0
    )

In [16]:
!pip install tqdm
from tqdm import tqdm
import numpy as np

Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (4.67.3)

In [17]:
X=[]
for k in tqdm(range(len(words))):
    X.append(avg_word2vec(words[k]))

X,len(X)

100%|██████████| 5569/5569 [00:01<00:00, 4043.76it/s]

([array([-0.04607704,  0.1747699 ,  0.01185505,  0.12941165,  0.01757257,
         -0.49692523,  0.10207366,  0.5486034 , -0.25418136, -0.16300514,
         -0.14164554, -0.3415856 , -0.10788094,  0.06984064,  0.0656274 ,
         -0.06988946,  0.07595021, -0.30548805,  0.04337269, -0.5944113 ,
          0.10471258,  0.14113122,  0.1191427 , -0.20786881, -0.03727868,
          0.01816426, -0.31144658, -0.1967068 , -0.21322618,  0.0988806 ,
          0.3390973 ,  0.04768844,  0.23142509, -0.16803977, -0.13099773,
          0.31274527,  0.03166257, -0.20713273, -0.16112089, -0.4847603 ,
         -0.01638615, -0.24352552, -0.09848852,  0.04632646,  0.19417495,
         -0.07918955, -0.18175578, -0.05572302,  0.05642496,  0.12195527,
          0.15375043, -0.23964724, -0.00401987,  0.02323701, -0.17932157,
          0.18673202,  0.11008748, -0.05591486, -0.24266402,  0.07871671,
          0.04912877, -0.00173731,  0.05361298, -0.05407364, -0.25163743,
          0.2042163 ,  0.20548378,  0.23003839, -0.360935  ,  0.26657224,
         -0.18967144,  0.1540996 ,  0.2980477 , -0.10589913,  0.32201073,
          0.10160539, -0.07097065, -0.01727376, -0.26593742,  0.11208538,
         -0.07533102,  0.00596873, -0.31246614,  0.38827753, -0.1386126 ,
         -0.06963264,  0.06532609,  0.2485932 ,  0.30929714,  0.05496353,
          0.24731202,  0.17482977,  0.01042152,  0.04443352,  0.47982666,
          0.2757417 ,  0.15778884, -0.18860617,  0.1574998 , -0.03282532],
        dtype=float32),
  array([-0.04471424,  0.17223673,  0.01464175,  0.12759763,  0.01935015,
         -0.47604787,  0.11482581,  0.51969784, -0.23400009, -0.15708087,
         -0.1334105 , -0.32275578, -0.09683328,  0.0599268 ,  0.0597689 ,
         -0.06492539,  0.07732634, -0.3013193 ,  0.03020499, -0.56417847,
          0.10009181,  0.1419143 ,  0.09787368, -0.20503755, -0.03640655,
          0.02337202, -0.308851  , -0.18326828, -0.2036888 ,  0.0880262 ,
          0.32537782,  0.04766454,  0.20742163, -0.16007741, -0.12356335,
          0.2951531 ,  0.03316964, -0.20231096, -0.14470077, -0.4692154 ,
         -0.0118212 , -0.2381955 , -0.09956299,  0.04642295,  0.19451061,
         -0.08254801, -0.17410667, -0.0484689 ,  0.05696178,  0.11942732,
          0.13738336, -0.23326439, -0.00317598,  0.02081168, -0.17341404,
          0.18302308,  0.10364476, -0.05752804, -0.22445214,  0.07663736,
          0.05002811, -0.0037188 ,  0.05906663, -0.05187239, -0.24734919,
          0.19862673,  0.19127268,  0.22692989, -0.33959892,  0.25629663,
         -0.17297508,  0.1543128 ,  0.28758615, -0.09827733,  0.31342787,
          0.09377632, -0.07258332, -0.02470783, -0.25677207,  0.0965637 ,
         -0.06742989,  0.0011432 , -0.30490762,  0.37325084, -0.1295838 ,
         -0.06632186,  0.05876134,  0.23863465,  0.298288  ,  0.05236106,
          0.23219526,  0.17526963,  0.01601177,  0.04523801,  0.45850354,
          0.2590866 ,  0.14545028, -0.17424467,  0.15151754, -0.0339473 ],
        dtype=float32),
  array([-3.88613418e-02,  1.91331476e-01,  3.41249724e-05,  1.79307997e-01,
          2.94506196e-02, -5.59288085e-01,  7.32828453e-02,  6.05877817e-01,
         -2.81098872e-01, -1.78931028e-01, -1.32243425e-01, -3.61038715e-01,
         -1.15168959e-01,  7.27527142e-02,  7.59747997e-02, -8.57058316e-02,
          7.31728375e-02, -3.57153505e-01,  4.96865883e-02, -6.67086601e-01,
          1.08799882e-01,  1.47306547e-01,  1.41519070e-01, -1.98227495e-01,
         -3.16963904e-02, -1.96888242e-02, -3.20889086e-01, -1.85557708e-01,
         -2.44851887e-01,  9.43480209e-02,  3.57275754e-01,  6.97481707e-02,
          2.43095458e-01, -1.62537828e-01, -1.29539028e-01,  3.51036102e-01,
          4.46764380e-02, -2.36173540e-01, -2.24253640e-01, -5.21343410e-01,
         -3.80597040e-02, -2.13673830e-01, -1.57441571e-01,  4.12263647e-02,
          1.75922424e-01, -6.86656609e-02, -2.23967209e-01, -6.92241117e-02,
          8.05795044e-02,  1.24576204e-01,  1.46759018e-01, -2.84246534e-01,
         -2.09883898e-02,  5.57243340e-02, -1.84594259e-01,  1.87542871e-01,
          9.23967361e-02, -7.52868578e-02, -2.93311119e-01,  8.88331681e-02,
          8.93218368e-02,  1.17972223e-02,  2.37820968e-02, -1.10326536e-01,
         -2.66624570e-01,  2.22507194e-01,  2.28185177e-01,  2.26499364e-01,
         -3.85205448e-01,  2.57497042e-01, -2.32078880e-01,  2.01967239e-01,
          3.02521050e-01, -1.27902508e-01,  3.29711795e-01,  1.17469996e-01,
         -5.08718155e-02, -3.28266784e-03, -2.74413228e-01,  1.05206735e-01,
         -6.40383065e-02,  2.55717505e-02, -3.16851020e-01,  4.56147850e-01,
         -1.51854217e-01, -6.51562065e-02,  3.71893086e-02,  2.56442040e-01,
          3.32014769e-01,  7.83716813e-02,  2.76137620e-01,  2.10005805e-01,
         -8.64155497e-03,  7.13071302e-02,  5.25094211e-01,  2.77062625e-01,
          1.54881269e-01, -2.19350249e-01,  1.70124233e-01, -3.84976529e-02],
        dtype=float32),
  array([-0.06195903,  0.2484333 ,  0.02572726,  0.16304398,  0.02465445,
         -0.6741754 ,  0.15370414,  0.73804957, -0.33605915, -0.22399831,
         -0.19071665, -0.4652916 , -0.13669881,  0.09153056,  0.09254494,
         -0.09598663,  0.11129008, -0.4078462 ,  0.04211257, -0.7954863 ,
          0.15200141,  0.19650565,  0.14217125, -0.28839993, -0.06474692,
          0.03641777, -0.43555468, -0.25948673, -0.27017134,  0.13582325,
          0.4563401 ,  0.06120069,  0.29769045, -0.2311194 , -0.17554367,
          0.41972923,  0.04712553, -0.2792759 , -0.18648414, -0.66238624,
         -0.01475971, -0.35381564, -0.12767732,  0.06082061,  0.26911548,
         -0.11259923, -0.24625078, -0.06140782,  0.07508232,  0.17181163,
          0.20735283, -0.32388353,  0.00942912,  0.01998991, -0.23425806,
          0.27064642,  0.15700473, -0.07511859, -0.31227043,  0.11359669,
          0.05605548, -0.00169477,  0.08392508, -0.06540579, -0.34090036,
          0.28472432,  0.27128604,  0.31991652, -0.48106954,  0.368982  ,
         -0.24785696,  0.19201744,  0.4091716 , -0.14274898,  0.44605806,
          0.13819687, -0.10861816, -0.03811273, -0.35806227,  0.14334679,
         -0.11468951,  0.00941728, -0.4292185 ,  0.5173664 , -0.17750095,
         -0.09180398,  0.09899648,  0.34002787,  0.41528183,  0.06866369,
          0.32855362,  0.22861637,  0.0271164 ,  0.05378727,  0.6453005 ,
          0.3716742 ,  0.21471469, -0.2544936 ,  0.21185175, -0.05319262],
        dtype=float32),
  array([-0.0519183 ,  0.20119776,  0.01903143,  0.13121068,  0.02203782,
         -0.54654795,  0.11178756,  0.5965616 , -0.2701873 , -0.17685406,
         -0.16027671, -0.37000415, -0.111045  ,  0.07882161,  0.07830182,
         -0.0746261 ,  0.08927402, -0.32318607,  0.03533549, -0.64061546,
          0.12487319,  0.16416536,  0.12865078, -0.23783523, -0.0424866 ,
          0.03384915, -0.3464751 , -0.1956336 , -0.21095085,  0.10896458,
          0.36778173,  0.05322223,  0.24043812, -0.18955563, -0.13766883,
          0.34223005,  0.03621895, -0.21813266, -0.15854459, -0.528783  ,
         -0.01500507, -0.28444153, -0.10696512,  0.04012316,  0.21065928,
         -0.08704992, -0.19598182, -0.04780589,  0.05897934,  0.13395143,
          0.16366957, -0.25459942, -0.00090892,  0.00884574, -0.17974849,
          0.21386607,  0.12725572, -0.05899346, -0.24907875,  0.09759233,
          0.0489004 , -0.00605436,  0.07120842, -0.05433038, -0.2600976 ,
          0.22666533,  0.22136809,  0.25177184, -0.38712072,  0.29994482,
         -0.1954572 ,  0.1474379 ,  0.32357976, -0.10675684,  0.35734975,
          0.10578239, -0.08000266, -0.03663358, -0.2812903 ,  0.1162354 ,
         -0.10169471,  0.00978502, -0.34669653,  0.41451287, -0.14699835,
         -0.07880235,  0.08649111,  0.26943764,  0.33820805,  0.0558277 ,
          0.26920137,  0.18047102,  0.02992636,  0.03299338,  0.5213043 ,
          0.2937257 ,  0.17159288, -0.20998198,  0.17054896, -0.04273212],
        dtype=float32),
  array([-0.05234373,  0.22283696,  0.01443319,  0.1632303 ,  0.02963668,
         -0.6239029 ,  0.11208963,  0.6787796 , -0.31361988, -0.20465887,
         -0.1727877 , -0.41811717, -0.12525174,  0.08870882,  0.09178733,
         -0.0789307 ,  0.10157475, -0.37427953,  0.04654895, -0.7252984 ,
          0.13310416,  0.17790607,  0.14788972, -0.25226015, -0.04559547,
          0.02565904, -0.385828  , -0.21459588, -0.24813278,  0.11434921,
          0.41271266,  0.05993808,  0.26946065, -0.20981492, -0.1582734 ,
          0.38316154,  0.04660628, -0.24900629, -0.19239318, -0.59192413,
         -0.02162975, -0.30126268, -0.13090822,  0.04913044,  0.23074567,
         -0.09091549, -0.23070906, -0.06122224,  0.07542728,  0.14556311,
          0.18097685, -0.2927674 , -0.00535773,  0.02205569, -0.20330437,
          0.23154327,  0.13553993, -0.07619044, -0.2878472 ,  0.11022305,
          0.05694959, -0.00144536,  0.06768505, -0.07417245, -0.29631463,
          0.26140735,  0.25325552,  0.27482164, -0.42809302,  0.3284059 ,
         -0.23041922,  0.17648248,  0.3611092 , -0.12241084,  0.39734295,
          0.12008616, -0.07661171, -0.02903632, -0.31263283,  0.11797385,
         -0.10759583,  0.01874414, -0.37653577,  0.47683543, -0.16734883,
         -0.08604318,  0.08091207,  0.29953647,  0.37741172,  0.06915575,
          0.3058123 ,  0.21548983,  0.02712354,  0.05000767,  0.5902783 ,
          0.3262916 ,  0.1851158 , -0.23390871,  0.19130008, -0.04656094],
        dtype=float32),
  array([-5.96463680e-02,  2.36911386e-01,  2.52373386e-02,  1.67198509e-01,
          2.81415377e-02, -6.61458015e-01,  1.37820214e-01,  7.25084007e-01,
         -3.39597553e-01, -2.18610719e-01, -1.92788795e-01, -4.51907575e-01,
         -1.34275541e-01,  9.02649537e-02,  9.51906070e-02, -8.10346082e-02,
          1.10083520e-01, -3.93045515e-01,  4.16357554e-02, -7.82347143e-01,
          1.46580607e-01,  1.96822926e-01,  1.62965491e-01, -2.88568795e-01,
         -5.43999411e-02,  4.28262837e-02, -4.20354813e-01, -2.42128804e-01,
         -2.62030423e-01,  1.29813865e-01,  4.50413018e-01,  6.19327687e-02,
          2.98220307e-01, -2.31252819e-01, -1.70278534e-01,  4.12732512e-01,
          4.05983329e-02, -2.68787742e-01, -1.98061660e-01, -6.43133461e-01,
         -1.43335760e-02, -3.40716839e-01, -1.27364069e-01,  5.56776039e-02,
          2.63347656e-01, -1.04167342e-01, -2.42308617e-01, -6.55046329e-02,
          7.35194832e-02,  1.59630388e-01,  2.01508254e-01, -3.10611486e-01,
          7.72657921e-04,  1.31669864e-02, -2.19942674e-01,  2.58243650e-01,
          1.50322080e-01, -7.16643780e-02, -3.06058615e-01,  1.15291558e-01,
          5.40400110e-02, -1.21784331e-02,  8.60296637e-02, -5.91250472e-02,
         -3.23417187e-01,  2.79758662e-01,  2.69244969e-01,  3.08899552e-01,
         -4.72456366e-01,  3.64254773e-01, -2.44611889e-01,  1.75693408e-01,
          3.95900100e-01, -1.28129855e-01,  4.31782246e-01,  1.27745286e-01,
         -8.79308805e-02, -4.10149470e-02, -3.43022376e-01,  1.39000043e-01,
         -1.22013144e-01,  1.28263831e-02, -4.20272171e-01,  5.05320728e-01,
         -1.82104096e-01, -9.88366455e-02,  9.96274352e-02,  3.26859742e-01,
          4.08761919e-01,  7.30481967e-02,  3.26156110e-01,  2.23684788e-01,
          3.01872101e-02,  4.60431017e-02,  6.39172971e-01,  3.61061335e-01,
          2.10892349e-01, -2.57069826e-01,  2.04182729e-01, -5.15143499e-02],
        dtype=float32),
  array([-0.04037073,  0.18683113,  0.01396766,  0.15083411,  0.02639798,
         -0.53730273,  0.07791318,  0.58847696, -0.27449363, -0.17299521,
         -0.14106792, -0.35712633, -0.10776073,  0.06584933,  0.0767777 ,
         -0.0617284 ,  0.07263992, -0.33474743,  0.04929743, -0.6407627 ,
          0.11119897,  0.14694628,  0.13550766, -0.21197324, -0.03549211,
          0.00176175, -0.3250908 , -0.18391672, -0.22680895,  0.09287664,
          0.34956208,  0.0589348 ,  0.24295035, -0.16207193, -0.13094963,
          0.33645225,  0.03988068, -0.22209817, -0.19877994, -0.50683665,
         -0.03288348, -0.23953602, -0.12867838,  0.0512355 ,  0.18810709,
         -0.07999087, -0.2106488 , -0.06401855,  0.06158199,  0.12341456,
          0.15400788, -0.25709766, -0.0139654 ,  0.0372723 , -0.18549548,
          0.18637979,  0.10369327, -0.06405981, -0.25916222,  0.08317373,
          0.05587929, -0.00088377,  0.04622075, -0.07986594, -0.26029885,
          0.2201769 ,  0.22238761,  0.22235444, -0.38128912,  0.26374295,
         -0.2127072 ,  0.16874968,  0.31232047, -0.10768092,  0.33419266,
          0.10928799, -0.05390336, -0.01438566, -0.2773539 ,  0.11230356,
         -0.07986509,  0.02145377, -0.31037122,  0.42508438, -0.15041511,
         -0.07090668,  0.05077578,  0.25926462,  0.33358887,  0.06895116,
          0.2695147 ,  0.2063652 ,  0.00874114,  0.0567659 ,  0.5114761 ,
          0.2863885 ,  0.16190764, -0.20612137,  0.17087427, -0.04241077],
        dtype=float32),
  array([-0.03658641,  0.20423432,  0.00458935,  0.18320812,  0.02304794,
         -0.58670264,  0.07206887,  0.6512418 , -0.29427224, -0.18462902,
         -0.14764522, -0.37748548, -0.12343112,  0.07618703,  0.07915528,
         -0.0713866 ,  0.07948478, -0.38201457,  0.04889455, -0.7063952 ,
          0.11618716,  0.1601287 ,  0.13989648, -0.22136006, -0.04328342,
         -0.01112735, -0.3457773 , -0.19971105, -0.24800155,  0.09818829,
          0.37151664,  0.06232887,  0.25221506, -0.16847639, -0.14167315,
          0.36000896,  0.04986431, -0.23530257, -0.2350795 , -0.5598372 ,
         -0.0468629 , -0.2514502 , -0.14922579,  0.04701728,  0.18469615,
         -0.08186968, -0.2347481 , -0.07136409,  0.08014247,  0.13891798,
          0.17007938, -0.29843605, -0.01104671,  0.0516296 , -0.19781953,
          0.19493406,  0.11836217, -0.06947677, -0.29880524,  0.09829903,
          0.07478207,  0.00324682,  0.01673219, -0.11278071, -0.27325448,
          0.24086675,  0.24076676,  0.23866706, -0.4048646 ,  0.2725278 ,
         -0.23084848,  0.19768299,  0.3398215 , -0.12463063,  0.35114962,
          0.11158699, -0.04629272, -0.00088999, -0.29515404,  0.11614706,
         -0.07816418,  0.0387491 , -0.3298236 ,  0.46825418, -0.16052017,
         -0.07387975,  0.0322899 ,  0.27841705,  0.35467687,  0.08445956,
          0.30868834,  0.23185965,  0.00519323,  0.08298796,  0.563389  ,
          0.29410213,  0.15947846, -0.22356519,  0.18938111, -0.05295757],
        dtype=float32),
  array([-0.03672077,  0.23240739, -0.00476912,  0.22067638,  0.04611101,
         -0.6669419 ,  0.07238963,  0.74088264, -0.34371617, -0.21333899,
         -0.16043732, -0.4314458 , -0.13173604,  0.08643389,  0.09728543,
         -0.09853379,  0.06946873, -0.43916973,  0.06436367, -0.8115464 ,
          0.1292218 ,  0.17469126,  0.16544823, -0.23800872, -0.03741932,
         -0.04377446, -0.38426536, -0.21264465, -0.30246028,  0.10275201,
          0.4344147 ,  0.08564008,  0.30645925, -0.177978  , -0.15570392,
          0.42829326,  0.05624136, -0.28569174, -0.29425317, -0.61729884,
         -0.05364076, -0.24938579, -0.19695702,  0.05567174,  0.20585851,
         -0.08161721, -0.27199546, -0.0916296 ,  0.10087729,  0.14735593,
          0.1768217 , -0.34939334, -0.02483126,  0.07494795, -0.2287676 ,
          0.21669164,  0.10096263, -0.08686119, -0.35415497,  0.09618124,
          0.1106422 ,  0.01691701,  0.02931406, -0.13440523, -0.33096385,
          0.2716143 ,  0.28105196,  0.26356307, -0.4677769 ,  0.3022779 ,
         -0.2854003 ,  0.24585459,  0.3647717 , -0.1519914 ,  0.3907108 ,
          0.13365683, -0.04456529,  0.00167094, -0.33486283,  0.14022595,
         -0.06790785,  0.03141673, -0.37723914,  0.55875665, -0.18646805,
         -0.07983956,  0.02888937,  0.30177388,  0.41688663,  0.09920543,
          0.34007752,  0.27162534, -0.02027459,  0.09340798,  0.6267588 ,
          0.3302338 ,  0.18052739, -0.25838193,  0.21354896, -0.05004793],
        dtype=float32),
  array([-0.04560904,  0.2159462 ,  0.01681363,  0.1404396 ,  0.02810319,
         -0.5887766 ,  0.11175503,  0.63606226, -0.29087096, -0.19469982,
         -0.16577525, -0.39135602, -0.11587307,  0.08175953,  0.08597387,
         -0.07329573,  0.09834666, -0.34508643,  0.03870256, -0.67823243,
          0.12507759,  0.16599607,  0.13400573, -0.24820751, -0.04548401,
          0.02983847, -0.3653766 , -0.20239379, -0.22224052,  0.11417205,
          0.38939407,  0.0549765 ,  0.2501776 , -0.20198002, -0.14871243,
          0.3564206 ,  0.04335488, -0.23088463, -0.16739747, -0.5597496 ,
         -0.0173495 , -0.2930289 , -0.10891683,  0.04282667,  0.21922919,
         -0.08760533, -0.21263891, -0.05225384,  0.06469511,  0.13501535,
          0.1683045 , -0.2660403 , -0.00400097,  0.01563448, -0.18507044,
          0.22480541,  0.13609907, -0.06294543, -0.2618061 ,  0.10387044,
          0.04577553, -0.00452579,  0.07075564, -0.06095183, -0.27277172,
          0.24783564,  0.23833638,  0.25593334, -0.40574846,  0.3077484 ,
         -0.21065566,  0.15596706,  0.34285572, -0.11044652,  0.3748728 ,
          0.11058804, -0.07827228, -0.03578559, -0.29761595,  0.11593088,
         -0.1043741 ,  0.0232618 , -0.36171114,  0.4380013 , -0.15744248,
         -0.08132248,  0.08282021,  0.28389007,  0.35683638,  0.06639356,
          0.28571624,  0.19951726,  0.02827015,  0.04055493,  0.5546057 ,
          0.30478254,  0.17569982, -0.2194558 ,  0.18201509, -0.04573515],
        dtype=float32),
  array([-4.71513011e-02,  2.25387678e-01,  1.68246939e-03,  2.03725666e-01,
          3.59893441e-02, -6.48165762e-01,  7.70135745e-02,  7.01552629e-01,
         -3.27786088e-01, -2.10264817e-01, -1.51778340e-01, -4.22693282e-01,
         -1.27607644e-01,  8.47237557e-02,  9.20273438e-02, -9.07568932e-02,
          8.41858089e-02, -4.11153913e-01,  5.49326688e-02, -7.71743953e-01,
          1.24985367e-01,  1.70512617e-01,  1.58253282e-01, -2.33625203e-01,
         -3.91957797e-02, -2.10541151e-02, -3.76575738e-01, -2.13304788e-01,
         -2.78846145e-01,  1.01821661e-01,  4.08686966e-01,  7.75955617e-02,
          2.75662810e-01, -1.90991312e-01, -1.51370347e-01,  4.00371164e-01,
          5.31647876e-02, -2.76158303e-01, -2.59146065e-01, -6.04511380e-01,
         -4.51003425e-02, -2.52043962e-01, -1.83283314e-01,  4.30804491e-02,
          2.00181335e-01, -7.95853958e-02, -2.60329127e-01, -6.95738569e-02,
          8.71008486e-02,  1.46094009e-01,  1.73331097e-01, -3.23129982e-01,
         -2.37336382e-02,  5.94541244e-02, -2.08767280e-01,  2.16680557e-01,
          1.18848100e-01, -8.23692009e-02, -3.29711825e-01,  1.08274050e-01,
          9.33817923e-02,  1.14747183e-02,  2.93491017e-02, -1.26057655e-01,
         -3.03333610e-01,  2.58334577e-01,  2.66082317e-01,  2.58500099e-01,
         -4.32759106e-01,  2.93389648e-01, -2.62978047e-01,  2.22250998e-01,
          3.49786669e-01, -1.39228597e-01,  3.85218740e-01,  1.29688799e-01,
         -5.43193668e-02, -8.88680294e-03, -3.20685565e-01,  1.13373436e-01,
         -8.21917355e-02,  3.62276025e-02, -3.60431731e-01,  5.29683292e-01,
         -1.80302188e-01, -7.37734139e-02,  4.53869477e-02,  3.00326109e-01,
          3.91206980e-01,  9.36491191e-02,  3.22207570e-01,  2.43955031e-01,
         -5.69918448e-05,  8.51127133e-02,  6.12400532e-01,  3.24670464e-01,
          1.73269317e-01, -2.56296068e-01,  2.01562926e-01, -4.74136136e-02],
        dtype=float32),
  array([-0.04554877,  0.23271862,  0.00133221,  0.20782651,  0.03636855,
         -0.66217685,  0.07895169,  0.73183185, -0.3355902 , -0.21364097,
         -0.16330199, -0.42881307, -0.13636841,  0.08267117,  0.09575228,
         -0.08755869,  0.08667388, -0.4272769 ,  0.05837348, -0.79618406,
          0.12690006,  0.17736685,  0.16442361, -0.24400508, -0.03919585,
         -0.01849241, -0.39031714, -0.22046556, -0.28542382,  0.11234391,
          0.4245161 ,  0.07483679,  0.28379285, -0.19408831, -0.15617499,
          0.41572738,  0.05258339, -0.27025723, -0.2706789 , -0.62297267,

In [18]:
def avg_word2vec(doc):
    return np.mean(
        [model.wv[word] for word in doc if word in model.wv.index_to_key]
        or [np.zeros(model.vector_size)],
        axis=0
    )

In [19]:
#create your independent feature
X_new=np.array(X)
X_new.shape()

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (5569,) + inhomogeneous part.

In [ ]:
#depentent fearture
y=pd.get_dummies(message['label'])
y=y.iloc[:,1].values
y

In [ ]:
for i,j,k in zip(X_new,y,message['message']) :
  print(i,j,k)

In [20]:
X[1]# this represent first sentence

array([-0.04471424,  0.17223673,  0.01464175,  0.12759763,  0.01935015,
       -0.47604787,  0.11482581,  0.51969784, -0.23400009, -0.15708087,
       -0.1334105 , -0.32275578, -0.09683328,  0.0599268 ,  0.0597689 ,
       -0.06492539,  0.07732634, -0.3013193 ,  0.03020499, -0.56417847,
        0.10009181,  0.1419143 ,  0.09787368, -0.20503755, -0.03640655,
        0.02337202, -0.308851  , -0.18326828, -0.2036888 ,  0.0880262 ,
        0.32537782,  0.04766454,  0.20742163, -0.16007741, -0.12356335,
        0.2951531 ,  0.03316964, -0.20231096, -0.14470077, -0.4692154 ,
       -0.0118212 , -0.2381955 , -0.09956299,  0.04642295,  0.19451061,
       -0.08254801, -0.17410667, -0.0484689 ,  0.05696178,  0.11942732,
        0.13738336, -0.23326439, -0.00317598,  0.02081168, -0.17341404,
        0.18302308,  0.10364476, -0.05752804, -0.22445214,  0.07663736,
        0.05002811, -0.0037188 ,  0.05906663, -0.05187239, -0.24734919,
        0.19862673,  0.19127268,  0.22692989, -0.33959892,  0.25629663,
       -0.17297508,  0.1543128 ,  0.28758615, -0.09827733,  0.31342787,
        0.09377632, -0.07258332, -0.02470783, -0.25677207,  0.0965637 ,
       -0.06742989,  0.0011432 , -0.30490762,  0.37325084, -0.1295838 ,
       -0.06632186,  0.05876134,  0.23863465,  0.298288  ,  0.05236106,
        0.23219526,  0.17526963,  0.01601177,  0.04523801,  0.45850354,
        0.2590866 ,  0.14545028, -0.17424467,  0.15151754, -0.0339473 ],
      dtype=float32)

In [21]:
X[0].reshape(1,-1).shape

(1, 100)

In [23]:
#this is first final indedependent feature
df_list = []
for i in range(0,len(X)):
  df_list.append(pd.DataFrame(X[i].reshape(1,-1)))
df = pd.concat(df_list, ignore_index=True)
df.head()

,0,1,2,3,4,5,6,7,8,9,...,1636,1637,1638,1639,1640,1641,1642,1643,1644,1645
0,-0.046077,0.174770,0.011855,0.129412,0.017573,-0.496925,0.102074,0.548603,-0.254181,-0.163005,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,-0.044714,0.172237,0.014642,0.127598,0.019350,-0.476048,0.114826,0.519698,-0.234000,-0.157081,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,-0.038861,0.191331,0.000034,0.179308,0.029451,-0.559288,0.073283,0.605878,-0.281099,-0.178931,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,-0.061959,0.248433,0.025727,0.163044,0.024654,-0.674175,0.153704,0.738050,-0.336059,-0.223998,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,-0.051918,0.201198,0.019031,0.131211,0.022038,-0.546548,0.111788,0.596562,-0.270187,-0.176854,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
#independent feature
X=df

In [27]:
#train test split
from sklearn.model_selection import train_test_split
#depentent fearture
y=pd.get_dummies(message['label'])
y=y.iloc[:,1].values
# Truncate y to match the number of samples in X
y = y[:len(X)]
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [28]:
X.isnull().sum()

0          0
1          0
2          0
3          0
4          0
        ...
1641    5558
1642    5558
1643    5558
1644    5558
1645    5558
Length: 1646, dtype: int64

In [30]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier(n_estimators=100,criterion='entropy')
classifier.fit(X_train,y_train)

RandomForestClassifier(criterion='entropy')

In [31]:
y_pred=classifier.predict(X_test)
#

In [35]:
classifier.score(X_test,y_test)

0.8590664272890485

In [37]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

       False       0.88      0.97      0.92       975
        True       0.24      0.06      0.09       139

    accuracy                           0.86      1114
   macro avg       0.56      0.52      0.51      1114
weighted avg       0.80      0.86      0.82      1114